export default {
  drawerIcon: require('../assests/Images/drawerIcon.png'),
  addIcon: require('../assests/Images/add_plus.png'),
  searchIcon: require('../assests/Images/search.png'),
  historyIcon: require('../assests/Images/history.png'),
  arrowRightIcon: require('../assests/Images/arrow_right.png'),
  arrowDownIcon: require('../assests/Images/arrow_down.png'),
  appLogo: require('../assests/Images/logo.png'),
  deleteIcon: require('../assests/Images/delete.png'),
  grainzLogo: require('../assests/Images/logo.png'),
  cancelIcon: require('../assests/Images/cancel.png'),
  checkIcon: require('../assests/Images/check.png'),
  calenderIcon: require('../assests/Images/calender.png'),
  doubleArrowIcon: require('../assests/Images/doubleArrow.png'),
  editIcon: require('../assests/Images/edit.png'),
};
